### PR TITLE
Touchstone integration instructions

### LINKED ISSUE #32: Describe the Touchstone integration process
Provide detailed instructions on integrating Touchstone authentication into a Django app via python-social-auth and SAML.

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Fixes #32 

#### What's this PR do?
Provides instructions on integrating Touchstone with Django.

#### How should this be manually tested?
N/A

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1: Looks good to me

**Comment by pdpinch** [comment]
No urgent, but @blarghmatey or @shaidar or @rhysyngsun could you review this for Matt?

**Comment by blarghmatey** [comment]
I already did :)

**Comment by mbertrand** [comment]
@blarghmatey to officially approve a PR, click 'Files changed' near the top, then 'Review changes', click the 'Approve' button, and submit.

**Pull request merged**
